# Generated by Django 5.2.7 on 2025-10-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('zone', models.CharField(max_length=10)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('shelf_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('OK', 'OK'), ('LOW_STOCK', 'LOW_STOCK'), ('CRITICAL', 'CRITICAL')], max_length=50, null=True)),
                ('scanned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('robot', models.ForeignKey(db_column='robot_id', on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
            options={
                'db_table': 'inventory_history',
            },
        ),
    ]
