# Generated by Django 5.2.7 on 2025-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('battery_level', models.IntegerField()),
                ('last_update', models.DateTimeField()),
                ('current_zone', models.CharField(max_length=10)),
                ('current_row', models.IntegerField()),
                ('current_shelf', models.IntegerField()),
            ],
        ),
    ]
